name: Print Hello Every 10 Seconds

on:
  workflow_dispatch:
  schedule:
    - cron: "0/5 * * * *"
jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "안녕"
